def addition(a, b):
    raise ValueError("fail case")

addition(2, 2)
